# mysql
spring:
  datasource:
    #Mysql配置
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/javam?useUnicode=true&characterEnco
    url: jdbc:mysql://localhost:3306/chat?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # 使用Alibaba的druid数据源，默认使用自带的
    type: com.alibaba.druid.pool.DruidDataSource

  # activemq配置
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

  jms:
    pub-sub-domain: true # 发布订阅模式

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

server:
  port: 9000