# mysql
spring:
  datasource:
    #Mysql配置
    driverClassName:  com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/javam?useUnicode=true&characterEnco
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # 使用Alibaba的druid数据源，默认使用自带的
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

server:
  port: 9000